-- gather ingredients
-- go to distillery
-- have still craft moonshine
-- pick it up when its done
-- moonshine gives +str
-- deliver to various saloons 
-- deliver to varior homesteads
-- moonshine cart is robbable by other players